type props = {
    id: string
    age: number
    gender: 'Male' | 'Female'
    amount: number
    status: 'APPROVED' | 'PENDING' | 'INPATIENT' | 'OUTPATIENT';
    email: string
    name: string
  }

export const data: props[]  = [
    {
        id: '23445133',
        age: 34,
        gender: 'Male',
        amount: 300,
        status: 'PENDING',
        email: 'test@example.com',
        name: 'Mr. Appiah Kubi'
    },
    {
        id: "87456321",
        age: 29,
        gender: "Male",
        amount: 350,
        status: "APPROVED",
        email: "john.doe@example.com",
        name: "Mr. John Doe",
      },
      {
        id: "19283475",
        age: 24,
        gender: "Female",
        amount: 400,
        status: "APPROVED",
        email: "jane.doe@example.com",
        name: "Ms. Jane Doe",
      },
      {
        id: "83746529",
        age: 36,
        gender: "Male",
        amount: 500,
        status: "PENDING",
        email: "kwame.adu@example.com",
        name: "Mr. Kwame Adu",
      },
      {
        id: "34215678",
        age: 42,
        gender: "Female",
        amount: 600,
        status: "PENDING",
        email: "ama.serwaa@example.com",
        name: "Ms. Ama Serwaa",
      },
      {
        id: "98734561",
        age: 31,
        gender: "Male",
        amount: 450,
        status: "APPROVED",
        email: "yaw.kusi@example.com",
        name: "Mr. Yaw Kusi",
      },
      {
        id: "74128963",
        age: 28,
        gender: "Female",
        amount: 300,
        status: "PENDING",
        email: "efua.ando@example.com",
        name: "Ms. Efua Ando",
      },
      {
        id: "56348291",
        age: 40,
        gender: "Male",
        amount: 380,
        status: "PENDING",
        email: "kojo.mensah@example.com",
        name: "Mr. Kojo Mensah",
      },
      {
        id: "81452637",
        age: 35,
        gender: "Female",
        amount: 420,
        status: "APPROVED",
        email: "aba.baah@example.com",
        name: "Ms. Aba Baah",
      },
      {
        id: "98534762",
        age: 37,
        gender: "Male",
        amount: 370,
        status: "APPROVED",
        email: "fiifi.boakye@example.com",
        name: "Mr. Fiifi Boakye",
      },
      {
        id: "26485937",
        age: 33,
        gender: "Female",
        amount: 310,
        status: "PENDING",
        email: "adjoa.manu@example.com",
        name: "Ms. Adjoa Manu",
      },
      {
        id: "48375129",
        age: 45,
        gender: "Male",
        amount: 550,
        status: "APPROVED",
        email: "kwesi.anan@example.com",
        name: "Mr. Kwesi Anan",
      },
      {
        id: "56784913",
        age: 26,
        gender: "Female",
        amount: 290,
        status: "PENDING",
        email: "afiwaa.bediako@example.com",
        name: "Ms. Afia Bediako",
      },
      {
        id: "72984356",
        age: 32,
        gender: "Male",
        amount: 480,
        status: "PENDING",
        email: "yaw.appiah@example.com",
        name: "Mr. Yaw Appiah",
      },
      {
        id: "38657249",
        age: 38,
        gender: "Female",
        amount: 320,
        status: "APPROVED",
        email: "akosua.nyarko@example.com",
        name: "Ms. Akosua Nyarko",
      },
      {
        id: "24375986",
        age: 41,
        gender: "Male",
        amount: 500,
        status: "PENDING",
        email: "daniel.asante@example.com",
        name: "Mr. Daniel Asante",
      },
]