type Payment = {
    id: string
    age: number
    gender: 'Male' | 'Female'
    amount: number
    status: 'APPROVED' | 'PENDING' | 'INPATIENT' | 'OUTPATIENT';
    email: string
    name: string
  }
  
  export const data: Payment[] = [
    {
      id: "28763421",
      age: 34,
      gender: "Female",
      amount: 200,
      status: 'OUTPATIENT',
      email: "alice@example.com",
      name: "Alice Johnson",
    },
    {
      id: "87635432",
      age: 42,
      gender: "Male",
      amount: 150,
      status: "INPATIENT",
      email: "bob@example.com",
      name: "Bob Martin",
    },
    {
      id: "34576324",
      age: 29,
      gender: "Male",
      amount: 100,
      status: "INPATIENT",
      email: "john@example.com",
      name: "John Smith",
    },
    {
      id: "12348765",
      age: 24,
      gender: "Female",
      amount: 300,
      status: "OUTPATIENT",
      email: "clara@example.com",
      name: "Clara Bennett",
    },
    {
      id: "65473829",
      age: 37,
      gender: "Male",
      amount: 400,
      status: "INPATIENT",
      email: "mike@example.com",
      name: "Mike Harris",
    },
    {
      id: "42387654",
      age: 31,
      gender: "Female",
      amount: 220,
      status: "OUTPATIENT",
      email: "sarah@example.com",
      name: "Sarah Brown",
    },
    {
      id: "98213476",
      age: 45,
      gender: "Male",
      amount: 180,
      status: "INPATIENT",
      email: "james@example.com",
      name: "James Clark",
    },
    {
      id: "12435478",
      age: 28,
      gender: "Female",
      amount: 150,
      status: "OUTPATIENT",
      email: "laura@example.com",
      name: "Laura Davis",
    },
    {
      id: "93457621",
      age: 33,
      gender: "Male",
      amount: 130,
      status: "INPATIENT",
      email: "peter@example.com",
      name: "Peter Evans",
    },
    {
      id: "67245318",
      age: 39,
      gender: "Female",
      amount: 250,
      status: "OUTPATIENT",
      email: "emily@example.com",
      name: "Emily Wilson",
    },
    {
      id: "76534219",
      age: 27,
      gender: "Male",
      amount: 120,
      status: "INPATIENT",
      email: "chris@example.com",
      name: "Chris Turner",
    },
    {
      id: "98451367",
      age: 41,
      gender: "Female",
      amount: 310,
      status: "OUTPATIENT",
      email: "angela@example.com",
      name: "Angela Moore",
    },
    {
      id: "64351278",
      age: 36,
      gender: "Male",
      amount: 170,
      status: "INPATIENT",
      email: "david@example.com",
      name: "David Adams",
    },
    {
      id: "89214365",
      age: 30,
      gender: "Female",
      amount: 200,
      status: "OUTPATIENT",
      email: "nina@example.com",
      name: "Nina Thompson",
    },
    {
      id: "45681234",
      age: 44,
      gender: "Male",
      amount: 140,
      status: "INPATIENT",
      email: "george@example.com",
      name: "George Carter",
    },
    {
      id: "98123465",
      age: 26,
      gender: "Female",
      amount: 190,
      status: "OUTPATIENT",
      email: "sophie@example.com",
      name: "Sophie Wright",
    },
    {
      id: "64351892",
      age: 38,
      gender: "Male",
      amount: 270,
      status: "INPATIENT",
      email: "henry@example.com",
      name: "Henry Scott",
    },
    {
      id: "98214356",
      age: 32,
      gender: "Female",
      amount: 220,
      status: "OUTPATIENT",
      email: "julie@example.com",
      name: "Julie Green",
    },
    {
      id: "74123689",
      age: 46,
      gender: "Male",
      amount: 310,
      status: "INPATIENT",
      email: "charles@example.com",
      name: "Charles Mitchell",
    },
    {
      id: "83941256",
      age: 35,
      gender: "Female",
      amount: 260,
      status: "OUTPATIENT",
      email: "emma@example.com",
      name: "Emma Robinson",
    },
  ];
  